Add zsh completion
containers/bubblewrap pull request #410
Opened 2021-03-12 12:16 UTC by haraldkubota

This is (so far) just the zsh completion file. No integration with autoconf, automake or making packages. Mainly because I've never used any of those tools and I likely will mess them up.

2021-03-21 11:17 UTC, haraldkubota commented
Anyone who could review this?

2021-04-19 10:05 UTC, smcv requested changes
To be useful, this will need to be installed, something like this (untested):


```
# in configure.ac
AC_ARG_WITH([zsh-completion-dir],
    AS_HELP_STRING([--with-zsh-completion-dir[=PATH]],
        [Install the zsh auto-completion script in this directory. @<:@default=yes@:>@]),
    [],
    [with_zsh_completion_dir=yes])

AS_IF([test "x$with_zsh_completion_dir" = "xyes"],
    [ZSH_COMPLETION_DIR='$datadir/zsh/site-functions"])
AC_SUBST([ZSH_COMPLETION_DIR])                                                   
AM_CONDITIONAL([ENABLE_ZSH_COMPLETION], [test "x$with_zsh_completion_dir" != "xno"])
```

```
# in Makefile.am
if ENABLE_ZSH_COMPLETION
zshcompletiondir = $(ZSH_COMPLETION_DIR
dist_zshcompletion_DATA = completions/zsh/_bwrap
endif
```

Just after the similar code for bash completions would probably be a good place to put these.

Try it with:

```
./autogen.sh
make
make install DESTDIR="$(pwd)/DESTDIR"
```

If all goes well you should find that the zsh completion is installed to `DESTDIR/usr/local/share/zsh/site-functions/_bwrap`.

2021-04-19 10:08 UTC, smcv commented
I don't really know zsh completion syntax, and we should check through the options and make sure they match what's implemented (particularly if any of my MRs that add new options get merged), but this looks really useful - thanks!

2021-04-25 03:56 UTC, haraldkubota commented on completions/zsh/_bwrap
> +    # $ egrep '#define\sCAP_\w+\s+[0-9]+' /usr/include/linux/capability.h | awk '{print $2}' | xargs echo
Yes, all_caps is defined once and then immediate used once.
I could not find a simple way to gather all kernel capabilities dynamically.

egrep...yeah, old school SysV user here.

2021-05-03 23:33 UTC, haraldkubota commented on completions/zsh/_bwrap
> +    # $ egrep '#define\sCAP_\w+\s+[0-9]+' /usr/include/linux/capability.h | awk '{print $2}' | xargs echo
Do I have to click on "Resolve conversation"?

2021-05-03 23:34 UTC, haraldkubota commented on completions/zsh/_bwrap
> +    CAP_MAC_ADMIN CAP_SYSLOG CAP_WAKE_ALARM CAP_BLOCK_SUSPEND CAP_AUDIT_READ
Removed already

2021-06-02 13:36 UTC, haraldkubota reviewed
Oh, I didn't realize that I can do the review!
Reviewed and cross-checked with the output of brwap --help and the options are not only in the same order as the command completions, but I cannot find anything extra or anything missing.

2021-06-10 10:11 UTC, smcv reviewed
Looks generally good, although I haven't tested it yet.

2021-06-10 10:17 UTC, smcv approved these changes
Seems to work nicely!

2021-06-10 16:46 UTC, smcv commented
@cgwalters, are you considering me to be enough of a maintainer that I can merge other people's branches (e.g. this one), or do you want power of veto?

2021-06-10 17:26 UTC, cgwalters commented
> @cgwalters, are you considering me to be enough of a maintainer that I can merge other people's branches (e.g. this one)

You're *at least* equal and have been doing more work, so please don't block on me!

(I skimmed this and it looks sane FWIW)

2021-06-10 17:55 UTC, merged