Add --foreground option
containers/bubblewrap pull request #588
Opened 2023-08-20 10:34 UTC by DaanDeMeyer

This option creates a new process group for the child process and if there's a controlling terminal, makes the new process group the foreground process group of the controlling terminal. This makes sure that SIGINT signals generated by CTRL+C are only sent to the child process and not to bubblewrap itself.

While this can also be achieved with external utilities (e.g. https://github.com/util-linux/util-linux/pull/2445), it still makes sense to support this natively in bubblewrap to avoid the need to install any other utilities in the sandbox to be able to make the child process the foreground process group of the controlling terminal.

Fixes #369

2024-02-05 11:24 UTC, smcv requested changes
Does this still work if the top-level sandboxed process is one that would normally `setpgid()` itself, like an interactive `bash` shell?

2024-02-05 11:24 UTC, smcv commented on bubblewrap.c
> +  if (opt_foreground) {
Please use GNU-style indentation:

```
  if (opt_foreground)
    {
      cleanup_fd int tty_fd = -1;
      ...
```

2024-02-05 11:24 UTC, smcv commented on bubblewrap.c
> +      if (tcsetpgrp (tty_fd, getpgid(0)) == -1)
Space before opening parenthesis:

```suggestion
      if (tcsetpgrp (tty_fd, getpgid (0)) == -1)
```

2024-02-05 11:24 UTC, smcv commented on bwrap.xml
> +      <term><option>--foreground</option></term>
I wonder whether this should have a name more like `--terminal-foreground` or `--tty-foreground`, to indicate that it isn't to do with daemonization or other things that might be referred to as "foreground" or "background"?

2024-02-05 11:24 UTC, smcv commented on bwrap.xml
> +        controlling terminal.
This seems like it's missing a mention of why this is useful to do things like resolving #369. Perhaps something like this:

```suggestion
	Create a new process group for the sandbox, and make it the
        foreground process group of the controlling terminal if there is a
        controlling terminal. This means that keyboard shortcuts that send
        signals, such as Ctrl+C for SIGINT or Ctrl+\ for SIGQUIT, will send
        the signal to the sandboxed process instead of to bubblewrap itself.
```

2024-08-19 14:19 UTC, closed without merging

2024-08-19 14:19 UTC, DaanDeMeyer commented
It turns out that for my use case reimplementing the bits I need from bubblewrap is easier than trying to fix the tool to support my use case so I'm closing this as I no longer need it.