Implement change proposed in "All MRs that add unit tests conflict with each other"
containers/bubblewrap pull request #602
Opened 2023-10-01 05:35 UTC by quag

Fixes containers/bubblewrap#420 using the proposed approach of defining ok(), done_testing(), and shifting the TAP plan from being written at the start to being written at the end. I also introduced an ok_skip() function, but I'm happy to change all uses to ok "# SKIP ..." if you prefer that.

This pull request also has two trivial fixes to the tests: 

1. A typo in a test case ("prefxing" -> "prefixing"
2. Switch the last /bin/bash to just bash (there are five references to bash, the other four--including #!/usr/bin/env bash-- all use the bash on the $PATH)

Let me know if you'd rather these two changes were in separate pull requests.

2023-10-01 12:01 UTC, smcv requested changes
This will need a rebase onto main with a small adjustment now that I've merged #598, but otherwise looks good. Thanks!

2023-10-01 12:03 UTC, smcv commented
Rebasing after I merged #599 will also require adding one extra `ok_skip`, I think.

2023-10-02 03:40 UTC, quag commented
Rebases done. Let me know if more are needed.

2023-10-02 09:06 UTC, smcv approved these changes

2023-10-02 09:06 UTC, merged