tests: use stat -c instead of --format for compatibility
containers/bubblewrap pull request #627
Opened 2024-04-19 13:47 UTC by sertonix

eg. busybox stat only has -c and not --format

2024-04-19 14:03 UTC, smcv requested changes
The change looks fine. Please add a `Signed-off-by` to indicate your acceptance of https://developercertificate.org/ as described in <https://github.com/containers/common/blob/main/CONTRIBUTING.md#sign-your-prs>.

2024-04-19 16:04 UTC, sertonix commented
Ok, done

2024-04-19 16:09 UTC, smcv commented
@alexlarsson, @cgwalters: Please confirm whether you are intending to enforce the rule that `Signed-off-by` must be from (something that looks like) a real name, and not from an obvious pseudonym?

This PR and #618 are both blocked by having a decision on that. I would personally be fine with a pseudonymous Signed-off-by, especially for small contributions - but I didn't write the rule, so I don't feel that I can be the one to change it.

2024-04-19 16:09 UTC, smcv approved these changes

2024-09-30 18:34 UTC, smcv commented
> @alexlarsson, @cgwalters: Please confirm whether you are intending to enforce the rule that `Signed-off-by` must be from (something that looks like) a real name, and not from an obvious pseudonym?
> 
> This PR and #618 are both blocked by having a decision on that.

Right, enough is enough: I've waited too long for a decision on whether this and several other simple fixes can be landed, and it's not like we can tell whether any given contribution is Signed-off-by someone's legal name or a plausible pseudonym anyway, so I'm going to say the answer is "yes" and start merging pseudonymous contributions.

@alexlarsson, @cgwalters, if this is a problem, please revert the relevant changes (and then get equivalent fixes some other way).

2024-09-30 18:50 UTC, smcv commented
> so I'm going to say the answer is "yes" and start merging pseudonymous contributions

(Except not right now, because unrelatedly the Github Actions configuration has regressed, so if anyone has objections to this, you have until the Actions are fixed to raise your objection.)

2024-09-30 19:01 UTC, merged

2024-09-30 22:03 UTC, cgwalters commented
It looks like the most canonical docs for this are https://github.com/cncf/foundation/blob/main/dco-guidelines.md

I believe the signoff line here qualifies.

2024-10-01 16:35 UTC, sertonix commented
> so I'm going to say the answer is "yes" and start merging pseudonymous contributions

Thank you!